using Edgewise.Domain.Engines.Positions;
using FsCheck.Xunit;
using Shouldly;

namespace Edgewise.Domain.Tests.Positions;

/// <summary>
/// Property-based tests. Random fill sequences are derived from FsCheck-generated byte
/// arrays (7 bytes per fill), keeping quantities and prices bounded and money math exact
/// (integer quantities, 2-decimal prices, 2-decimal minor unit), so the conservation
/// identity must hold to the exact minor unit.
/// </summary>
public class PositionBuilderPropertyTests
{
    private static readonly DateTime BaseTime = new(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc);

    private static List<FillEvent> MapFills(byte[] data)
    {
        var fills = new List<FillEvent>();
        for (var i = 0; i + 7 <= data.Length; i += 7)
        {
            var qty = (decimal)((data[i] % 20) + 1);
            var priceCents = (((data[i + 1] << 8) | data[i + 2]) % 9900) + 100;
            var price = priceCents / 100m;
            var side = data[i + 3] % 2 == 0 ? Side.Buy : Side.Sell;
            long fee = data[i + 4] * 2;
            long funding = data[i + 5] % 50;
            var pin = (data[i + 6] % 4) switch
            {
                2 => "P1",
                3 => "P2",
                _ => (string?)null,
            };
            fills.Add(new FillEvent(
                $"fill-{fills.Count}",
                BaseTime.AddMinutes(fills.Count),
                side,
                qty,
                price,
                fee,
                funding,
                pin));
        }

        return fills;
    }

    [Property(MaxTest = 300, EndSize = 500)]
    public void Conservation_RealisedPlusMarkToLastEqualsIndependentCashDelta(byte[]? data)
    {
        var fills = MapFills(data ?? []);
        var trades = PositionBuilder.Build("SIM", fills, TestMoney.ToMinor);

        // Fees and funding are never created or destroyed (incl. pro-rata flip splits).
        trades.Sum(t => t.FeesMinor).ShouldBe(fills.Sum(f => f.FeeMinor));
        trades.Sum(t => t.FundingMinor).ShouldBe(fills.Sum(f => f.FundingMinor));

        if (fills.Count == 0)
        {
            trades.ShouldBeEmpty();
            return;
        }

        // Independent portfolio accounting straight from the raw fills:
        // trading cash delta (sells add cash, buys consume it) plus the liquidation value
        // of the residual net position at the last traded price.
        var lastPrice = fills[^1].Price;
        var signedNotionalMinor = fills.Sum(f =>
            TestMoney.ToMinor((f.Side == Side.Sell ? 1m : -1m) * f.Qty * f.Price));
        var netQty = fills.Sum(f => f.Side == Side.Buy ? f.Qty : -f.Qty);
        var independentWealthMinor = signedNotionalMinor + TestMoney.ToMinor(netQty * lastPrice);

        // Engine-side accounting: realised PnL over all trades plus open trades
        // marked to the last price against their remaining FIFO lots.
        var realisedMinor = trades.Sum(t => t.RealisedPnlMinor);
        var unrealisedMinor = trades
            .Where(t => t.Status == TradeStatus.Open)
            .Sum(t =>
            {
                var dir = t.Direction == TradeDirection.Long ? 1m : -1m;
                return TestMoney.ToMinor(
                    t.OpenLots.Sum(l => (lastPrice - l.Price) * l.Qty * dir));
            });

        (realisedMinor + unrealisedMinor).ShouldBe(independentWealthMinor);

        // The signed open quantity across all open trades equals the raw net position.
        trades
            .Where(t => t.Status == TradeStatus.Open)
            .Sum(t => (t.Direction == TradeDirection.Long ? 1m : -1m) * t.RemainingQty)
            .ShouldBe(netQty);

        // Closed trades hold no residual quantity or lots.
        foreach (var closed in trades.Where(t => t.Status == TradeStatus.Closed))
        {
            closed.RemainingQty.ShouldBe(0m);
            closed.OpenLots.ShouldBeEmpty();
        }
    }

    [Property(MaxTest = 200, EndSize = 500)]
    public void Rebuild_IsIdempotentAndDeterministic(byte[]? data)
    {
        var fills = MapFills(data ?? []);

        var first = PositionBuilder.Build("SIM", fills, TestMoney.ToMinor);
        var second = PositionBuilder.Build("SIM", fills, TestMoney.ToMinor);

        TradeAssert.ShouldDeepEqual(second, first);

        // Rebuilding from a shuffled-but-timestamped copy is also stable, because the
        // engine stably sorts by timestamp before processing.
        var reversedInput = fills.AsEnumerable().Reverse().ToList();
        var third = PositionBuilder.Build("SIM", reversedInput, TestMoney.ToMinor);
        TradeAssert.ShouldDeepEqual(third, first);
    }
}
